steps:
- id: Install dependencies
  name: 'node:10.15.1'
  entrypoint: yarn
  args: ['install']
- id: Run lint on project source
  name: 'node:10.15.1'
  entrypoint: yarn
  args: ['lint']
- id: Run CI tests
  name: 'node:10.15.1'
  entrypoint: yarn
  args: ['test:ci']
- id: Presubmit Linter
  name: 'node:10.15.1'
  entrypoint: bash
  args: ['./scripts/git-presubmit-linter.bash']
# Integration tests
- id: Install test project dependencies
  name: 'node:10.15.1'
  entrypoint: yarn
  args: ['install']
  dir: 'test'
- id: Install locally generated package
  name: 'node:10.15.1'
  entrypoint: yarn
  # This value needs to change on every version update
  args: ['add', './../typedoc-neo-theme-v1.0.9.tgz'] # Install locally generated package
  dir: 'test'
- id: Generate test project docs
  name: 'node:10.15.1'
  entrypoint: yarn
  args: ['docs']
  dir: 'test'
- id: Compare generated docs to expectation
  name: 'node:10.15.1'
  entrypoint: bash
  args: ['./compare.sh']
  dir: 'test'
artifacts:
  objects:
    # Store generated files in a Cloud Storage bucket with the commit hash as directory
    location: 'gs://typedoc-neo-theme/$SHORT_SHA'
    paths: ['*.tgz']